name: Test Action
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
  merge_group:
  workflow_dispatch:

jobs:
  push-ghcr:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    steps:
      - name: Perform checkout
        uses: actions/checkout@v4

      - name: Fetch specs
        run: |
          wget https://raw.githubusercontent.com/ublue-os/packages/main/staging/devpod/devpod.spec
          wget https://raw.githubusercontent.com/ublue-os/packages/refs/heads/main/staging/scx-scheds/scx-scheds.spec
          wget https://raw.githubusercontent.com/ublue-os/packages/refs/heads/main/staging/kf6-kio/kf6-kio.spec

      - name: Test rpmlint (single file)
        uses: ./
        with:
          rpmfiles: ./devpod.spec
          permissive: 'true'

      - name: Test rpmlint (multiple files)
        uses: ./
        with:
          rpmfiles: './devpod.spec, ./scx-scheds.spec'
          permissive: 'true'

      - name: Test rpmlint with rpkg
        uses: ./
        with:
          rpmfiles: ./kf6-kio.spec
          rpkg: 'true'
